var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");}var ca=ba(this);
function c(a,b){if(b)a:{var d=ca;a=a.split(".");for(var g=0;g<a.length-1;g++){var k=a[g];if(!(k in d))break a;d=d[k]}a=a[a.length-1];g=d[a];b=b(g);b!=g&&null!=b&&aa(d,a,{configurable:!0,writable:!0,value:b})}}c("Array.prototype.fill",function(a){return a?a:function(b,d,g){var k=this.length||0;0>d&&(d=Math.max(0,k+d));if(null==g||g>k)g=k;g=Number(g);0>g&&(g=Math.max(0,k+g));for(d=Number(d||0);d<g;d++)this[d]=b;return this}});function e(a){return a?a:Array.prototype.fill}
c("Int8Array.prototype.fill",e);c("Uint8Array.prototype.fill",e);c("Uint8ClampedArray.prototype.fill",e);c("Int16Array.prototype.fill",e);c("Uint16Array.prototype.fill",e);c("Int32Array.prototype.fill",e);c("Uint32Array.prototype.fill",e);c("Float32Array.prototype.fill",e);c("Float64Array.prototype.fill",e);
c("String.prototype.startsWith",function(a){return a?a:function(b,d){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var g=this.length,k=b.length;d=Math.max(0,Math.min(d|0,this.length));for(var m=0;m<k&&d<g;)if(this[d++]!=b[m++])return!1;return m>=k}});window.kaRun=da;window.kaFormat=ea;window.kaStop=f;
window.easykey=fa;window.easyrun=h;window.easygo=ha;window.easyinit=l;window.easyinp=ia;var n=[],p=0,q=null,r=null,t=null,u;function v(a){if(q=a)q.j=!1,300==q.width&&150==q.height&&(q.width=800,q.height=800)}function ha(a,b,d){b=void 0===b?null:b;d=void 0===d?null:d;v(b);b&&w();if(r=d)r.value="";u=!0;x.postMessage(["run",a,2,-1,null])}function h(a,b,d){n.push([a,void 0===b?null:b,void 0===d?null:d]);0==p&&l(n[0][1]);2>p||(q&&q.j?f():y())}
function y(){if(!u&&0!=n.length){var a=null,b=n.shift();1<b.length&&v(b[1]);2<b.length&&(a=b[2]);w();u=!0;x.postMessage(["runx",b[0],0,-1,a])}}function z(a,b){t&&t(a,void 0===b?null:b)}function w(){A();B=q.getContext("2d");C(8);B.lineWidth=1;D(3);B.g=0;B.h=0;B.o=null;B.m=null;B.setTransform(1,0,0,1,0,0);B.translate(.04,.04);B.scale(8,8)}var E=!1;function da(a,b,d,g){b=void 0===b?null:b;d=void 0===d?0:d;g=void 0===g?-1:g;(q=F)&&w();E=!1;255<d&&(G=null,E=!0);u=!1;x.postMessage(["run",a,d,g,b])}
function ea(a,b){b=void 0===b?null:b;null==b?x.postMessage(["format",a]):x&&x.postMessage(["formatID",a,b])}function ja(){x.terminate();H()}var I;function f(){J();q&&q.j?(x.postMessage(["stop_ping"]),A(),I=setTimeout(ja,500)):(x.terminate(),H())}var B=null;function K(){q.i&&(clearTimeout(q.i),q.i=null)}
function A(){q&&q.j&&(q.j=!1,q.onmouseout=null,q.onmousedown=null,q.onmouseup=null,q.onmousemove=null,q.ontouchmove=null,q.ontouchstart=null,q.ontouchend=null,q.removeEventListener("keydown",L),q.removeAttribute("tabIndex"),q.l&&(cancelAnimationFrame(q.l),q.l=null),K(),q.style.cursor="default")}function M(a,b){var d=B.lineWidth/2;B.beginPath();B.arc(a,b,d,0,2*Math.PI);B.fill()}function C(a){B.font=""+Math.round(a)+"px monospace";B.u=5*a/6}
function D(a){if(1==a)B.save(),B.setTransform(1,0,0,1,0,0),B.o?B.putImageData(B.o,0,0):B.m?(B.fillStyle=B.m,B.fillRect(0,0,800,800)):B.clearRect(0,0,800,800),B.restore();else if(2==a)B.save(),B.setTransform(1,0,0,1,0,0),B.o=B.getImageData(0,0,800,800),B.m=null,B.restore();else if(3==a)a=window.getComputedStyle(q,null).color,B.fillStyle=a,B.strokeStyle=a;else if(4==a){for(a=q;;){var b=window.getComputedStyle(a,null).backgroundColor;if(b.startsWith("rgb("))break;a=a.parentNode;if(null==a){b="rgb(0,0,0)";
break}}B.fillStyle=b;B.strokeStyle=b}else console.log("** sys "+a+" not handled")}var G;
function N(a){switch(a[0]){case 1:B.g=a[1];B.h=a[2];break;case 2:var b=a[1];a=a[2];B.beginPath();B.moveTo(B.g,B.h);B.lineTo(b,a);B.stroke();M(B.g,B.h);M(b,a);B.g=b;B.h=a;break;case 3:B.beginPath();B.arc(B.g,B.h,a[1],0,2*Math.PI);B.fill();break;case 4:B.fillRect(B.g,B.h,a[1],1*a[2]);break;case 5:b=a[1];if(!(2>b.length)){B.beginPath();B.moveTo(b[0][0],b[0][1]);for(a=1;a<b.length;a++)B.lineTo(b[a][0],b[a][1]);B.fill()}break;case 6:B.fillText(a[1],B.g,B.h+B.u);break;case 7:D(a[1]);break;case 8:B.lineWidth=
a[1];break;case 9:b="rgb("+a[1]+","+a[2]+","+a[3]+")";B.fillStyle=b;B.strokeStyle=b;break;case 10:C(a[1]);break;case 11:q.j&&a[1]<O.length&&(q.style.cursor=O[a[1]]);break;case 12:b=a[1];if(!(2>b.length)){a=b[0][0];var d=b[0][1];M(a,d);B.beginPath();B.moveTo(a,d);if(2==b.length){var g=b[1][0],k=b[1][1];B.lineTo(a,d)}else{for(var m=1;;){a=b[m][0];d=b[m][1];g=b[m+1][0];k=b[m+1][1];if(m==b.length-2)break;B.quadraticCurveTo(a,d,(a+g)/2,(d+k)/2);m+=1}B.quadraticCurveTo(a,d,g,k)}B.stroke();M(g,k)}break;
case 13:B.translate(a[1],a[2]);break;case 14:B.rotate(a[1]);break;case 15:B.m="rgb("+a[1]+","+a[2]+","+a[3]+")";B.o=null;break;case 16:B.beginPath(),B.arc(B.g,B.h,a[1],a[2]*Math.PI/180,a[3]*Math.PI/180),B.fill()}}var O=["default","crosshair","pointer"];
function ka(a){if(1==a.length)a=a[0],E&&7>=a[0]&&G&&B.putImageData(G,8*B.g-8,8*B.h-8),N(a),E&&7>=a[0]&&(G=B.getImageData(8*B.g-8,8*B.h-8,16,16),a=B.fillStyle,B.fillStyle="red",B.beginPath(),B.arc(B.g,B.h,1,0,2*Math.PI),B.fill(),B.fillStyle=a);else for(var b=0;b<a.length;b++)N(a[b])}var P=null,Q;function J(){P&&(P.close(),P.i&&clearTimeout(P.i),P=null)}
function R(){var a=Q.shift(),b=1E3*a[1];P.s.frequency.setValueAtTime(a[0],P.currentTime);P.gain.gain.setTargetAtTime(1,P.currentTime,.01);P.i=setTimeout(la,b)}function la(){P.gain.gain.setTargetAtTime(0,P.currentTime,.05);0!=Q.length&&(P.i=setTimeout(R,150))}function S(){P=new (window.AudioContext||window.webkitAudioContext);P.s=P.createOscillator();P.gain=P.createGain();P.gain.gain.setValueAtTime(0,P.currentTime);P.s.connect(P.gain);P.gain.connect(P.destination);P.s.start()}
function ma(a){P||S();P.i&&(clearTimeout(P.i),P.gain.gain.setTargetAtTime(0,P.currentTime,.05));Q=a;0!=Q.length&&R()}var T=!1;function U(a){var b=q.getBoundingClientRect();T=!0;var d=q.width/b.width/8;x.postMessage(["mouse",0,(a.clientX-b.left)*d,(a.clientY-b.top)*d]);q.focus();a.preventDefault()}function na(a){V=a.touches[0];a.clientX=V.clientX;a.clientY=V.clientY;U(a)}
function W(a){var b=q.getBoundingClientRect();T=!1;var d=q.width/b.width/8;x.postMessage(["mouse",1,(a.clientX-b.left)*d,(a.clientY-b.top)*d]);a.preventDefault()}function oa(a){var b=q.getBoundingClientRect(),d=q.width/b.width/8;x.postMessage(["mouse",2,(a.clientX-b.left)*d,(a.clientY-b.top)*d]);a.preventDefault()}function pa(a){if(r){var b=r.value;6E4<b.length&&(b=b.substr(1E3));r.value=b+a;r.scrollTop=r.scrollHeight}else console.log(a)}
function X(){P?(P.resume(),"running"==P.state&&(q.removeEventListener("mousedown",X),q.removeEventListener("touchstart",X),q.removeEventListener("touchend",X))):S()}var V;
function qa(a){a=a.data;switch(a[0]){case "list":ka(a[1]);break;case "print":pa(a[1]);break;case "ide":a.shift();var b=a.shift();z(b,a);break;case "stderr":console.log(a[1]);break;case "started":console.log("started");window.sab=null;"function"==typeof SharedArrayBuffer&&(window.sab=new SharedArrayBuffer(112));x.postMessage(["init",window.sab,navigator.language.substring(0,2)]);1==p&&Y(null);p=2;u=!1;y();z("ready");break;case "done":E&&G&&B.putImageData(G,8*B.g-8,8*B.h-8);u=!1;A();z("stopped");y();
break;case "stop_pong":clearTimeout(I);u=!1;z("stopped");y();break;case "sound":ma(a[1]);break;case "timer":q.j&&ra(a[1]);break;case "init":if(0==(a[1]&32))break;if(!q){console.log("no canvas");x.terminate();z("info",[0]);H();break}z("canvon");q.j=!0;a[1]&15&&(q.focus(),a[1]&1&&(q.onmousedown=U,q.ontouchstart=na),a[1]&2&&(q.onmouseup=W,q.ontouchend=function(d){d.clientX=V.clientX;d.clientY=V.clientY;W(d)},q.onmouseout=function(d){T&&(d.clientX=0,d.clientY=0,W(d))},0==(a[1]&4)&&(q.ontouchmove=function(d){V=
d.touches[0]})),a[1]&4&&(q.onmousemove=oa,q.ontouchmove=function(d){V=d.touches[0];d.clientX=V.clientX;d.clientY=V.clientY;oa(d)}),a[1]&8&&(q.addEventListener("keydown",L,!1),q.tabIndex=0));a[1]&16&&!q.l&&(q.l=requestAnimationFrame(sa));a[1]&64&&(q.addEventListener("mousedown",X),q.addEventListener("touchstart",X),q.addEventListener("touchend",X));break;case "exit":A();J();x.terminate();z("info",[0]);H();break;case "error":u=!1;z("error");break;default:console.log("unknown command: "+a)}}
function H(){x=new Worker("easyw181.js");x.onmessage=qa}function ta(){x.postMessage(["timer"])}function ra(a){K();0<=a&&(q.i=setTimeout(ta,1E3*a))}function sa(){x.postMessage(["animate"]);q.l=requestAnimationFrame(sa)}function L(a){x.postMessage(["key",a.key]);a.preventDefault()}var x=null,F=null;function Y(a){r?a?pa(a+"\n"):r.value="":q&&(a?(w(),B.fillText(a,10,10)):B&&D(1))}
function l(a,b,d){r=void 0===b?null:b;t=void 0===d?null:d;F=a;v(a);"object"!=typeof WebAssembly?(Y("no wasm support"),z("nowasm")):(H(),setTimeout(function(){1==p&&Y("Loading ...")},1E3));p=1}function fa(a){x.postMessage(["key",a])}function ia(a){var b=new Uint16Array(window.sab);if(a){b[4]=a.length+1;for(var d=0;d<a.length;d++)b[d+5]=a.charCodeAt(d)}else b[4]=0;b=new Int32Array(window.sab);Atomics.store(b,1,1);Atomics.notify?Atomics.notify(b,1,1):Atomics.wake(b,1,1)}
if(window.easyscript){var Z=window.easycanv;Z||(Z=document.querySelector("canvas"));h(window.easyscript,Z)};
