var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var g=a[d];if(!(g in c))return;c=c[g]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var g=a.split(".");a=1===g.length;d=g[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var k=0;k<g.length-1;k++){var f=g[k];if(!(f in d))return;d=d[f]}g=g[g.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[g]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,g,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[g]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[g]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(g):$jscomp.POLYFILL_PREFIX+c+"$"+g),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[g],{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=$jscomp.checkStringArgs(this,b,"startsWith");b+="";var g=d.length,k=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var f=0;f<k&&c<g;)if(d[c++]!=b[f++])return!1;return f>=k}},"es6","es3");
$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(f){return f instanceof g?f:new g(function(h,m){h(f)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(f){if(null==this.batch_){this.batch_=[];var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})}this.batch_.push(f)};
var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(f){d(f,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var f=this.batch_;this.batch_=[];for(var h=0;h<f.length;++h){var m=f[h];f[h]=null;try{m()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(f){this.asyncExecuteFunction(function(){throw f;})};var g=function(f){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var h=this.createResolveAndReject_();
try{f(h.resolve,h.reject)}catch(m){h.reject(m)}};g.prototype.createResolveAndReject_=function(){function f(l){return function(q){m||(m=!0,l.call(h,q))}}var h=this,m=!1;return{resolve:f(this.resolveTo_),reject:f(this.reject_)}};g.prototype.resolveTo_=function(f){if(f===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof g)this.settleSameAsPromise_(f);else{a:switch(typeof f){case "object":var h=null!=f;break a;case "function":h=!0;break a;default:h=!1}h?this.resolveToNonPromiseObj_(f):
this.fulfill_(f)}};g.prototype.resolveToNonPromiseObj_=function(f){var h=void 0;try{h=f.then}catch(m){this.reject_(m);return}"function"==typeof h?this.settleSameAsThenable_(h,f):this.fulfill_(f)};g.prototype.reject_=function(f){this.settle_(2,f)};g.prototype.fulfill_=function(f){this.settle_(1,f)};g.prototype.settle_=function(f,h){if(0!=this.state_)throw Error("Cannot settle("+f+", "+h+"): Promise already settled in state"+this.state_);this.state_=f;this.result_=h;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};g.prototype.scheduleUnhandledRejectionCheck_=function(){var f=this;d(function(){if(f.notifyUnhandledRejection_()){var h=$jscomp.global.console;"undefined"!==typeof h&&h.error(f.result_)}},1)};g.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var f=$jscomp.global.CustomEvent,h=$jscomp.global.Event,m=$jscomp.global.dispatchEvent;if("undefined"===typeof m)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):
"function"===typeof h?f=new h("unhandledrejection",{cancelable:!0}):(f=$jscomp.global.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.result_;return m(f)};g.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var f=0;f<this.onSettledCallbacks_.length;++f)k.asyncExecute(this.onSettledCallbacks_[f]);this.onSettledCallbacks_=null}};var k=new b;g.prototype.settleSameAsPromise_=function(f){var h=this.createResolveAndReject_();
f.callWhenSettled_(h.resolve,h.reject)};g.prototype.settleSameAsThenable_=function(f,h){var m=this.createResolveAndReject_();try{f.call(h,m.resolve,m.reject)}catch(l){m.reject(l)}};g.prototype.then=function(f,h){function m(r,e){return"function"==typeof r?function(n){try{l(r(n))}catch(p){q(p)}}:e}var l,q,t=new g(function(r,e){l=r;q=e});this.callWhenSettled_(m(f,l),m(h,q));return t};g.prototype.catch=function(f){return this.then(void 0,f)};g.prototype.callWhenSettled_=function(f,h){function m(){switch(l.state_){case 1:f(l.result_);
break;case 2:h(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?k.asyncExecute(m):this.onSettledCallbacks_.push(m);this.isRejectionHandled_=!0};g.resolve=c;g.reject=function(f){return new g(function(h,m){m(f)})};g.race=function(f){return new g(function(h,m){for(var l=$jscomp.makeIterator(f),q=l.next();!q.done;q=l.next())c(q.value).callWhenSettled_(h,m)})};g.all=function(f){var h=$jscomp.makeIterator(f),m=h.next();return m.done?c([]):new g(function(l,
q){function t(n){return function(p){r[n]=p;e--;0==e&&l(r)}}var r=[],e=0;do r.push(void 0),e++,c(m.value).callWhenSettled_(t(r.length-1),q),m=h.next();while(!m.done)})};return g},"es6","es3");
$jscomp.polyfill("Array.prototype.copyWithin",function(a){function b(c){c=Number(c);return Infinity===c||-Infinity===c?c:c|0}return a?a:function(c,d,g){var k=this.length;c=b(c);d=b(d);g=void 0===g?k:b(g);c=0>c?Math.max(k+c,0):Math.min(c,k);d=0>d?Math.max(k+d,0):Math.min(d,k);g=0>g?Math.max(k+g,0):Math.min(g,k);if(c<d)for(;d<g;)d in this?this[c++]=this[d++]:(delete this[c++],d++);else for(g=Math.min(g,k+d-c),c+=g-d;g>d;)--g in this?this[--c]=this[g]:delete this[--c];return this}},"es6","es3");
$jscomp.typedArrayCopyWithin=function(a){return a?a:Array.prototype.copyWithin};$jscomp.polyfill("Int8Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint8Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint8ClampedArray.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Int16Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");
$jscomp.polyfill("Uint16Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Int32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Float32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Float64Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");
$jscomp.polyfill("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var g=d.length;c=c||0;for(0>c&&(c=Math.max(c+g,0));c<g;c++){var k=d[c];if(k===b||Object.is(k,b))return!0}return!1}},"es7","es3");
$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,c||0)}},"es6","es3");var Module="undefined"!==typeof Module?Module:{},moduleOverrides={},key;for(key in Module)Module.hasOwnProperty(key)&&(moduleOverrides[key]=Module[key]);
var arguments_=[],thisProgram="./this.program",quit_=function(a,b){throw b;},ENVIRONMENT_IS_WEB="object"===typeof window,ENVIRONMENT_IS_WORKER="function"===typeof importScripts,ENVIRONMENT_IS_NODE="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,scriptDirectory="";function locateFile(a){return Module.locateFile?Module.locateFile(a,scriptDirectory):scriptDirectory+a}var read_,readAsync,readBinary,setWindowTitle,nodeFS,nodePath;
if(ENVIRONMENT_IS_NODE)scriptDirectory=ENVIRONMENT_IS_WORKER?require("path").dirname(scriptDirectory)+"/":__dirname+"/",read_=function(a,b){nodeFS||(nodeFS=require("fs"));nodePath||(nodePath=require("path"));a=nodePath.normalize(a);return nodeFS.readFileSync(a,b?null:"utf8")},readBinary=function(a){a=read_(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},readAsync=function(a,b,c){nodeFS||(nodeFS=require("fs"));nodePath||(nodePath=require("path"));a=nodePath.normalize(a);nodeFS.readFile(a,
function(d,g){d?c(d):b(g.buffer)})},1<process.argv.length&&(thisProgram=process.argv[1].replace(/\\/g,"/")),arguments_=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=Module),process.on("uncaughtException",function(a){if(!(a instanceof ExitStatus))throw a;}),process.on("unhandledRejection",abort),quit_=function(a,b){if(keepRuntimeAlive())throw process.exitCode=a,b;process.exit(a)},Module.inspect=function(){return"[Emscripten Module object]"};else if(ENVIRONMENT_IS_WEB||ENVIRONMENT_IS_WORKER)ENVIRONMENT_IS_WORKER?
scriptDirectory=self.location.href:"undefined"!==typeof document&&document.currentScript&&(scriptDirectory=document.currentScript.src),scriptDirectory=0!==scriptDirectory.indexOf("blob:")?scriptDirectory.substr(0,scriptDirectory.lastIndexOf("/")+1):"",read_=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ENVIRONMENT_IS_WORKER&&(readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},setWindowTitle=function(a){document.title=a};var out=Module.print||console.log.bind(console),err=Module.printErr||console.warn.bind(console);for(key in moduleOverrides)moduleOverrides.hasOwnProperty(key)&&(Module[key]=moduleOverrides[key]);moduleOverrides=null;Module.arguments&&(arguments_=Module.arguments);
Module.thisProgram&&(thisProgram=Module.thisProgram);Module.quit&&(quit_=Module.quit);var wasmBinary;Module.wasmBinary&&(wasmBinary=Module.wasmBinary);var noExitRuntime=Module.noExitRuntime||!0;"object"!==typeof WebAssembly&&abort("no native wasm support detected");var wasmMemory,ABORT=!1,EXITSTATUS;function assert(a,b){a||abort("Assertion failed: "+b)}function getCFunc(a){var b=Module["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function ccall(a,b,c,d,g){g={string:function(l){var q=0;if(null!==l&&void 0!==l&&0!==l){var t=(l.length<<2)+1;q=stackAlloc(t);stringToUTF8(l,q,t)}return q},array:function(l){var q=stackAlloc(l.length);writeArrayToMemory(l,q);return q}};a=getCFunc(a);var k=[],f=0;if(d)for(var h=0;h<d.length;h++){var m=g[c[h]];m?(0===f&&(f=stackSave()),k[h]=m(d[h])):k[h]=d[h]}c=a.apply(null,k);return c=function(l){0!==f&&stackRestore(f);l="string"===b?UTF8ToString(l):"boolean"===b?!!l:l;return l}(c)}
var UTF8Decoder="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function UTF8ArrayToString(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&UTF8Decoder)return UTF8Decoder.decode(a.subarray(b,c));for(d="";b<c;){var g=a[b++];if(g&128){var k=a[b++]&63;if(192==(g&224))d+=String.fromCharCode((g&31)<<6|k);else{var f=a[b++]&63;g=224==(g&240)?(g&15)<<12|k<<6|f:(g&7)<<18|k<<12|f<<6|a[b++]&63;65536>g?d+=String.fromCharCode(g):(g-=65536,d+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else d+=String.fromCharCode(g)}return d}
function UTF8ToString(a,b){return a?UTF8ArrayToString(HEAPU8,a,b):""}
function stringToUTF8Array(a,b,c,d){if(!(0<d))return 0;var g=c;d=c+d-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var h=a.charCodeAt(++k);f=65536+((f&1023)<<10)|h&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0;return c-g}
function stringToUTF8(a,b,c){return stringToUTF8Array(a,HEAPU8,b,c)}function lengthBytesUTF8(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function allocateUTF8(a){var b=lengthBytesUTF8(a)+1,c=_malloc(b);c&&stringToUTF8Array(a,HEAP8,c,b);return c}function writeArrayToMemory(a,b){HEAP8.set(a,b)}function alignUp(a,b){0<a%b&&(a+=b-a%b);return a}
var buffer,HEAP8,HEAPU8,HEAP16,HEAPU16,HEAP32,HEAPU32,HEAPF32,HEAPF64;function updateGlobalBufferAndViews(a){buffer=a;Module.HEAP8=HEAP8=new Int8Array(a);Module.HEAP16=HEAP16=new Int16Array(a);Module.HEAP32=HEAP32=new Int32Array(a);Module.HEAPU8=HEAPU8=new Uint8Array(a);Module.HEAPU16=HEAPU16=new Uint16Array(a);Module.HEAPU32=HEAPU32=new Uint32Array(a);Module.HEAPF32=HEAPF32=new Float32Array(a);Module.HEAPF64=HEAPF64=new Float64Array(a)}
var INITIAL_MEMORY=Module.INITIAL_MEMORY||16777216,wasmTable,__ATPRERUN__=[],__ATINIT__=[],__ATMAIN__=[],__ATPOSTRUN__=[],runtimeInitialized=!1,runtimeExited=!1,runtimeKeepaliveCounter=0;function keepRuntimeAlive(){return noExitRuntime||0<runtimeKeepaliveCounter}function preRun(){if(Module.preRun)for("function"==typeof Module.preRun&&(Module.preRun=[Module.preRun]);Module.preRun.length;)addOnPreRun(Module.preRun.shift());callRuntimeCallbacks(__ATPRERUN__)}
function initRuntime(){runtimeInitialized=!0;callRuntimeCallbacks(__ATINIT__)}function preMain(){callRuntimeCallbacks(__ATMAIN__)}function exitRuntime(){runtimeExited=!0}function postRun(){if(Module.postRun)for("function"==typeof Module.postRun&&(Module.postRun=[Module.postRun]);Module.postRun.length;)addOnPostRun(Module.postRun.shift());callRuntimeCallbacks(__ATPOSTRUN__)}function addOnPreRun(a){__ATPRERUN__.unshift(a)}function addOnInit(a){__ATINIT__.unshift(a)}
function addOnPostRun(a){__ATPOSTRUN__.unshift(a)}var runDependencies=0,runDependencyWatcher=null,dependenciesFulfilled=null;function addRunDependency(a){runDependencies++;Module.monitorRunDependencies&&Module.monitorRunDependencies(runDependencies)}
function removeRunDependency(a){runDependencies--;Module.monitorRunDependencies&&Module.monitorRunDependencies(runDependencies);0==runDependencies&&(null!==runDependencyWatcher&&(clearInterval(runDependencyWatcher),runDependencyWatcher=null),dependenciesFulfilled&&(a=dependenciesFulfilled,dependenciesFulfilled=null,a()))}Module.preloadedImages={};Module.preloadedAudios={};
function abort(a){if(Module.onAbort)Module.onAbort(a);a+="";err(a);ABORT=!0;EXITSTATUS=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}var dataURIPrefix="data:application/octet-stream;base64,";function isDataURI(a){return a.startsWith(dataURIPrefix)}function isFileURI(a){return a.startsWith("file://")}var wasmBinaryFile;wasmBinaryFile="easyw.wasm";isDataURI(wasmBinaryFile)||(wasmBinaryFile=locateFile(wasmBinaryFile));
function getBinary(a){try{if(a==wasmBinaryFile&&wasmBinary)return new Uint8Array(wasmBinary);if(readBinary)return readBinary(a);throw"both async and sync fetching of the wasm failed";}catch(b){abort(b)}}
function getBinaryPromise(){if(!wasmBinary&&(ENVIRONMENT_IS_WEB||ENVIRONMENT_IS_WORKER)){if("function"===typeof fetch&&!isFileURI(wasmBinaryFile))return fetch(wasmBinaryFile,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+wasmBinaryFile+"'";return a.arrayBuffer()}).catch(function(){return getBinary(wasmBinaryFile)});if(readAsync)return new Promise(function(a,b){readAsync(wasmBinaryFile,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return getBinary(wasmBinaryFile)})}
function createWasm(){function a(g,k){Module.asm=g.exports;wasmMemory=Module.asm.m;updateGlobalBufferAndViews(wasmMemory.buffer);wasmTable=Module.asm.y;addOnInit(Module.asm.n);removeRunDependency("wasm-instantiate")}function b(g){a(g.instance)}function c(g){return getBinaryPromise().then(function(k){return WebAssembly.instantiate(k,d)}).then(function(k){return k}).then(g,function(k){err("failed to asynchronously prepare wasm: "+k);abort(k)})}var d={a:asmLibraryArg};addRunDependency("wasm-instantiate");
if(Module.instantiateWasm)try{return Module.instantiateWasm(d,a)}catch(g){return err("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||isDataURI(wasmBinaryFile)||isFileURI(wasmBinaryFile)||"function"!==typeof fetch?c(b):fetch(wasmBinaryFile,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,d).then(b,function(k){err("wasm streaming compile failed: "+k);err("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}}
var ASM_CONSTS={7660:function(){update()},7669:function(a){postMessage(["timer",a])},7699:function(a){postMessage(["init",a])},7729:function(a){postMessage(["ide","info",a])},7766:function(a){postMessage(["ide","selline",a])},7806:function(a){postMessage(["ide","output",UTF8ToString(a)])},7858:function(a){postMessage(["print",UTF8ToString(a)+"\n"])},7910:function(a){postMessage(["print",UTF8ToString(a)])},7955:function(a,b,c){push([9,a,b,c])},7980:function(a){push([6,UTF8ToString(a)])},8011:function(a,
b){push([1,a,b])},8032:function(a,b){push([13,a,b])},8054:function(a){push([14,a])},8072:function(a,b,c){push([15,a,b,c])},8098:function(a,b){push([2,a,b])},8119:function(a,b){push([4,a,b])},8140:function(a,b,c){push([16,a,b,c])},8166:function(a){push([3,a])},8183:function(a){push([8,a])},8200:function(a){push([7,a])},8217:function(a){push([10,a])},8235:function(a){push([11,a])},8253:function(){update();postMessage(["exit"])},8285:function(){list=[]},8295:function(a,b){list.push([a,b])},8319:function(){push([5,
list])},8335:function(){list=[]},8345:function(a,b){list.push([a,b])},8369:function(){push([12,list])},8386:function(){list=[]},8396:function(a,b){list.push([a,b])},8420:function(){postMessage(["sound",list]);list=[]},8460:function(){postMessage(["done"])},8482:function(){step()},8489:function(){input()},8497:function(){postMessage(["started"])},8522:function(){return lang.charCodeAt(0)+256*lang.charCodeAt(1)}};
function callRuntimeCallbacks(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(Module);else{var c=b.func;"number"===typeof c?void 0===b.arg?wasmTable.get(c)():wasmTable.get(c)(b.arg):c(void 0===b.arg?null:b.arg)}}}function handleException(a){if(a instanceof ExitStatus||"unwind"==a)return EXITSTATUS;err("exception thrown: "+a);quit_(1,a)}
function _tzset_impl(){function a(f){return(f=f.toTimeString().match(/\(([A-Za-z ]+)\)$/))?f[1]:"GMT"}var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var g=d.getTimezoneOffset(),k=Math.max(b,g);HEAP32[__get_timezone()>>2]=60*k;HEAP32[__get_daylight()>>2]=Number(b!=g);c=a(c);d=a(d);c=allocateUTF8(c);d=allocateUTF8(d);g<b?(HEAP32[__get_tzname()>>2]=c,HEAP32[__get_tzname()+4>>2]=d):(HEAP32[__get_tzname()>>2]=d,HEAP32[__get_tzname()+4>>2]=c)}
function _tzset(){_tzset.called||(_tzset.called=!0,_tzset_impl())}
function _localtime_r(a,b){_tzset();a=new Date(1E3*HEAP32[a>>2]);HEAP32[b>>2]=a.getSeconds();HEAP32[b+4>>2]=a.getMinutes();HEAP32[b+8>>2]=a.getHours();HEAP32[b+12>>2]=a.getDate();HEAP32[b+16>>2]=a.getMonth();HEAP32[b+20>>2]=a.getFullYear()-1900;HEAP32[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;HEAP32[b+28>>2]=d;HEAP32[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==
Math.min(c,d))|0;HEAP32[b+32>>2]=a;a=HEAP32[__get_tzname()+(a?4:0)>>2];HEAP32[b+40>>2]=a;return b}function ___localtime_r(a,b){return _localtime_r(a,b)}var readAsmConstArgsArray=[];function readAsmConstArgs(a,b){readAsmConstArgsArray.length=0;var c;for(b>>=2;c=HEAPU8[a++];)(c=105>c)&&b&1&&b++,readAsmConstArgsArray.push(c?HEAPF64[b++>>1]:HEAP32[b]),++b;return readAsmConstArgsArray}function _emscripten_asm_const_int(a,b,c){b=readAsmConstArgs(b,c);return ASM_CONSTS[a].apply(null,b)}
function _emscripten_memcpy_big(a,b,c){HEAPU8.copyWithin(a,b,b+c)}function _emscripten_random(){return Math.random()}function emscripten_realloc_buffer(a){try{return wasmMemory.grow(a-buffer.byteLength+65535>>>16),updateGlobalBufferAndViews(wasmMemory.buffer),1}catch(b){}}
function _emscripten_resize_heap(a){var b=HEAPU8.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.min(2147483648,alignUp(Math.max(a,d),65536));if(emscripten_realloc_buffer(d))return!0}return!1}var _emscripten_get_now;_emscripten_get_now=ENVIRONMENT_IS_NODE?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};
function _emscripten_thread_sleep(a){for(var b=_emscripten_get_now();_emscripten_get_now()-b<a;);}function _exit(a){exit(a)}var SYSCALLS={mappings:{},buffers:[null,[],[]],printChar:function(a,b){var c=SYSCALLS.buffers[a];0===b||10===b?((1===a?out:err)(UTF8ArrayToString(c,0)),c.length=0):c.push(b)},varargs:void 0,get:function(){SYSCALLS.varargs+=4;return HEAP32[SYSCALLS.varargs-4>>2]},getStr:function(a){return UTF8ToString(a)},get64:function(a,b){return a}};function _fd_close(a){return 0}
function _fd_seek(a,b,c,d,g){}function _fd_write(a,b,c,d){for(var g=0,k=0;k<c;k++){for(var f=HEAP32[b+8*k>>2],h=HEAP32[b+(8*k+4)>>2],m=0;m<h;m++)SYSCALLS.printChar(a,HEAPU8[f+m]);g+=h}HEAP32[d>>2]=g;return 0}function _gettimeofday(a){var b=Date.now();HEAP32[a>>2]=b/1E3|0;HEAP32[a+4>>2]=b%1E3*1E3|0;return 0}function __isLeapYear(a){return 0===a%4&&(0!==a%100||0===a%400)}function __arraySum(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var __MONTH_DAYS_LEAP=[31,29,31,30,31,30,31,31,30,31,30,31],__MONTH_DAYS_REGULAR=[31,28,31,30,31,30,31,31,30,31,30,31];function __addDays(a,b){for(a=new Date(a.getTime());0<b;){var c=__isLeapYear(a.getFullYear()),d=a.getMonth();c=(c?__MONTH_DAYS_LEAP:__MONTH_DAYS_REGULAR)[d];if(b>c-a.getDate())b-=c-a.getDate()+1,a.setDate(1),11>d?a.setMonth(d+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function _strftime(a,b,c,d){function g(e,n,p){for(e="number"===typeof e?e.toString():e||"";e.length<n;)e=p[0]+e;return e}function k(e,n){return g(e,n,"0")}function f(e,n){function p(v){return 0>v?-1:0<v?1:0}var u;0===(u=p(e.getFullYear()-n.getFullYear()))&&0===(u=p(e.getMonth()-n.getMonth()))&&(u=p(e.getDate()-n.getDate()));return u}function h(e){switch(e.getDay()){case 0:return new Date(e.getFullYear()-1,11,29);case 1:return e;case 2:return new Date(e.getFullYear(),0,3);case 3:return new Date(e.getFullYear(),
0,2);case 4:return new Date(e.getFullYear(),0,1);case 5:return new Date(e.getFullYear()-1,11,31);case 6:return new Date(e.getFullYear()-1,11,30)}}function m(e){e=__addDays(new Date(e.tm_year+1900,0,1),e.tm_yday);var n=new Date(e.getFullYear(),0,4),p=new Date(e.getFullYear()+1,0,4);n=h(n);p=h(p);return 0>=f(n,e)?0>=f(p,e)?e.getFullYear()+1:e.getFullYear():e.getFullYear()-1}var l=HEAP32[d+40>>2];d={tm_sec:HEAP32[d>>2],tm_min:HEAP32[d+4>>2],tm_hour:HEAP32[d+8>>2],tm_mday:HEAP32[d+12>>2],tm_mon:HEAP32[d+
16>>2],tm_year:HEAP32[d+20>>2],tm_wday:HEAP32[d+24>>2],tm_yday:HEAP32[d+28>>2],tm_isdst:HEAP32[d+32>>2],tm_gmtoff:HEAP32[d+36>>2],tm_zone:l?UTF8ToString(l):""};c=UTF8ToString(c);l={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U",
"%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in l)c=c.replace(new RegExp(q,"g"),l[q]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),r="January February March April May June July August September October November December".split(" ");l={"%a":function(e){return t[e.tm_wday].substring(0,3)},"%A":function(e){return t[e.tm_wday]},"%b":function(e){return r[e.tm_mon].substring(0,3)},"%B":function(e){return r[e.tm_mon]},"%C":function(e){return k((e.tm_year+1900)/100|
0,2)},"%d":function(e){return k(e.tm_mday,2)},"%e":function(e){return g(e.tm_mday,2," ")},"%g":function(e){return m(e).toString().substring(2)},"%G":function(e){return m(e)},"%H":function(e){return k(e.tm_hour,2)},"%I":function(e){e=e.tm_hour;0==e?e=12:12<e&&(e-=12);return k(e,2)},"%j":function(e){return k(e.tm_mday+__arraySum(__isLeapYear(e.tm_year+1900)?__MONTH_DAYS_LEAP:__MONTH_DAYS_REGULAR,e.tm_mon-1),3)},"%m":function(e){return k(e.tm_mon+1,2)},"%M":function(e){return k(e.tm_min,2)},"%n":function(){return"\n"},
"%p":function(e){return 0<=e.tm_hour&&12>e.tm_hour?"AM":"PM"},"%S":function(e){return k(e.tm_sec,2)},"%t":function(){return"\t"},"%u":function(e){return e.tm_wday||7},"%U":function(e){var n=new Date(e.tm_year+1900,0,1),p=0===n.getDay()?n:__addDays(n,7-n.getDay());e=new Date(e.tm_year+1900,e.tm_mon,e.tm_mday);return 0>f(p,e)?(n=__arraySum(__isLeapYear(e.getFullYear())?__MONTH_DAYS_LEAP:__MONTH_DAYS_REGULAR,e.getMonth()-1)-31,p=31-p.getDate()+n+e.getDate(),k(Math.ceil(p/7),2)):0===f(p,n)?"01":"00"},
"%V":function(e){var n=new Date(e.tm_year+1901,0,4),p=h(new Date(e.tm_year+1900,0,4));n=h(n);var u=__addDays(new Date(e.tm_year+1900,0,1),e.tm_yday);if(0>f(u,p))return"53";if(0>=f(n,u))return"01";e=p.getFullYear()<e.tm_year+1900?e.tm_yday+32-p.getDate():e.tm_yday+1-p.getDate();return k(Math.ceil(e/7),2)},"%w":function(e){return e.tm_wday},"%W":function(e){var n=new Date(e.tm_year,0,1),p=1===n.getDay()?n:__addDays(n,0===n.getDay()?1:7-n.getDay()+1);e=new Date(e.tm_year+1900,e.tm_mon,e.tm_mday);return 0>
f(p,e)?(n=__arraySum(__isLeapYear(e.getFullYear())?__MONTH_DAYS_LEAP:__MONTH_DAYS_REGULAR,e.getMonth()-1)-31,p=31-p.getDate()+n+e.getDate(),k(Math.ceil(p/7),2)):0===f(p,n)?"01":"00"},"%y":function(e){return(e.tm_year+1900).toString().substring(2)},"%Y":function(e){return e.tm_year+1900},"%z":function(e){e=e.tm_gmtoff;var n=0<=e;e=Math.abs(e)/60;return(n?"+":"-")+String("0000"+(e/60*100+e%60)).slice(-4)},"%Z":function(e){return e.tm_zone},"%%":function(){return"%"}};for(q in l)c.includes(q)&&(c=c.replace(new RegExp(q,
"g"),l[q](d)));q=intArrayFromString(c,!1);if(q.length>b)return 0;writeArrayToMemory(q,a);return q.length-1}function intArrayFromString(a,b,c){c=0<c?c:lengthBytesUTF8(a)+1;c=Array(c);a=stringToUTF8Array(a,c,0,c.length);b&&(c.length=a);return c}
var asmLibraryArg={h:___localtime_r,a:_emscripten_asm_const_int,l:_emscripten_memcpy_big,e:_emscripten_random,f:_emscripten_resize_heap,g:_emscripten_thread_sleep,b:_exit,i:_fd_close,k:_fd_seek,d:_fd_write,c:_gettimeofday,j:_strftime},asm=createWasm(),___wasm_call_ctors=Module.___wasm_call_ctors=function(){return(___wasm_call_ctors=Module.___wasm_call_ctors=Module.asm.n).apply(null,arguments)},_errstr=Module._errstr=function(){return(_errstr=Module._errstr=Module.asm.o).apply(null,arguments)},_malloc=
Module._malloc=function(){return(_malloc=Module._malloc=Module.asm.p).apply(null,arguments)},_evt_func=Module._evt_func=function(){return(_evt_func=Module._evt_func=Module.asm.q).apply(null,arguments)},_evt_mouse=Module._evt_mouse=function(){return(_evt_mouse=Module._evt_mouse=Module.asm.r).apply(null,arguments)},_parse=Module._parse=function(){return(_parse=Module._parse=Module.asm.s).apply(null,arguments)},_format=Module._format=function(){return(_format=Module._format=Module.asm.t).apply(null,
arguments)},_caret=Module._caret=function(){return(_caret=Module._caret=Module.asm.u).apply(null,arguments)},_k_free=Module._k_free=function(){return(_k_free=Module._k_free=Module.asm.v).apply(null,arguments)},_exec=Module._exec=function(){return(_exec=Module._exec=Module.asm.w).apply(null,arguments)},_main=Module._main=function(){return(_main=Module._main=Module.asm.x).apply(null,arguments)},__get_tzname=Module.__get_tzname=function(){return(__get_tzname=Module.__get_tzname=Module.asm.z).apply(null,
arguments)},__get_daylight=Module.__get_daylight=function(){return(__get_daylight=Module.__get_daylight=Module.asm.A).apply(null,arguments)},__get_timezone=Module.__get_timezone=function(){return(__get_timezone=Module.__get_timezone=Module.asm.B).apply(null,arguments)},stackSave=Module.stackSave=function(){return(stackSave=Module.stackSave=Module.asm.C).apply(null,arguments)},stackRestore=Module.stackRestore=function(){return(stackRestore=Module.stackRestore=Module.asm.D).apply(null,arguments)},stackAlloc=
Module.stackAlloc=function(){return(stackAlloc=Module.stackAlloc=Module.asm.E).apply(null,arguments)};Module.ccall=ccall;var calledRun;function ExitStatus(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}var calledMain=!1;dependenciesFulfilled=function runCaller(){calledRun||run();calledRun||(dependenciesFulfilled=runCaller)};
function callMain(a){a=Module._main;try{var b=a(0,0);exit(b,!0);return b}catch(c){return handleException(c)}finally{calledMain=!0}}
function run(a){function b(){if(!calledRun&&(calledRun=!0,Module.calledRun=!0,!ABORT)){initRuntime();preMain();if(Module.onRuntimeInitialized)Module.onRuntimeInitialized();shouldRunNow&&callMain(a);postRun()}}a=a||arguments_;0<runDependencies||(preRun(),0<runDependencies||(Module.setStatus?(Module.setStatus("Running..."),setTimeout(function(){setTimeout(function(){Module.setStatus("")},1);b()},1)):b()))}Module.run=run;function exit(a,b){EXITSTATUS=a;keepRuntimeAlive()||exitRuntime();procExit(a)}
function procExit(a){EXITSTATUS=a;if(!keepRuntimeAlive()){if(Module.onExit)Module.onExit(a);ABORT=!0}quit_(a,new ExitStatus(a))}if(Module.preInit)for("function"==typeof Module.preInit&&(Module.preInit=[Module.preInit]);0<Module.preInit.length;)Module.preInit.pop()();var shouldRunNow=!0;Module.noInitialRun&&(shouldRunNow=!1);run();function update(){0<cmds.length&&(postMessage(["list",cmds]),cmds=[])}function push(a){cmds.push(a);1E4<cmds.length&&update()}
onmessage=function(a){a=a.data;var b=a[0];if("mouse"==b)Module.ccall("evt_mouse","null",["int","float","float"],[a[1],a[2],a[3]]),update();else if("animate"==b)Module.ccall("evt_func","null",["int","string"],[1,null]),update();else if("timer"==b)Module.ccall("evt_func","null",["int","string"],[2,null]),update();else if("key"==b)Module.ccall("evt_func","null",["int","string"],[0,a[1]]),update();else if("stop_ping"==b)Module.ccall("k_free","null",null,null),postMessage(["stop_pong"]);else if("init"==
b)sab=a[1],lang=a[2];else if("run"==b){b=Module.ccall("parse","int",["string","int","int"],[a[1],a[2],a[3]]);var c=Module.ccall("format","string",null,null),d=Module.ccall("caret","int",null,null);0<=b?(a=Module.ccall("errstr","string",null,null),postMessage(["ide","src_err",c,b,d,a])):(postMessage(["ide","src",c,b,d]),cmds=[],a=Module.ccall("exec",null,["int","string"],[a[2],a[4]]),update(),0==a&&postMessage(["done"]))}else"runx"==b?(b=Module.ccall("parse","int",["string","int","int"],[a[1],a[2],
a[3]]),0<=b?postMessage(["error"]):(cmds=[],a=Module.ccall("exec",null,["int","string"],[a[2],a[4]]),update(),0==a&&postMessage(["done"]))):"format"==b?(b=Module.ccall("parse","int",["string","int","int"],[a[1],14,0]),c=Module.ccall("format","string",null,null),d=Module.ccall("caret","int",null,null),a=Module.ccall("errstr","string",null,null),postMessage(["ide","src_nl",c,b,d,a])):"formatID"==b?(Module.ccall("parse","int",["string","int","int"],[a[1],6,0]),c=Module.ccall("format","string",null,null),
postMessage(["ide","src2",c,a[2]])):"error"==b&&(a=Module.ccall("error","string",null,null),postMessage(["ide","error",a]))};
function input(){if(null==sab){var a="ERROR: 'input' does not work, because 'SharedArrayBuffer' is disabled in your browser\n";console.log(a);postMessage(["ide","print",a])}else update(),postMessage(["ide","input"]),a=new Int32Array(sab),Atomics.wait(a,1,0),Atomics.store(a,1,0),a=new Uint16Array(sab),0!=a[4]?(a=String.fromCharCode.apply(null,a.slice(5,a[4]+4)),Module.ccall("evt_func","null",["int","string"],[3,a])):Module.ccall("evt_func","null",["int","string"],[4,""])}
function step(){update();postMessage(["ide","step"]);var a=new Int32Array(sab);Atomics.wait(a,0,0);Atomics.store(a,0,0);Module.ccall("evt_func","null",["int"],[5+a[2]])};
